#!/bin/bash

# The purpose of this script is to do things with files generated by
# 'create-react-app' after 'build' is run.
# 1. Remove all files inside 'static' folder at project root (up one directory level)
# 2. Move files up one directory level to 'static' folder

echo 'Clearing out previous build'
cd ../static
rm -r ./*

echo 'Moving latest built into static folder'
cd ../client/
cp -R ./build/ ../static/
